server.port: 8080
server.servlet.context-path: /
author:
  name: liuxunming
  csdnUrl: http://blog.csdn.net/diyangxia
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xmliu?serverTimezone=UTC
    username: root
    password: 123456